name: document-explainer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.8
  - pip
  - pip:
    - openai
    - python-dotenv
    - PyMuPDF
    - beautifulsoup4
    - tiktoken
    - numpy
